name: Next.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.16.0' 

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install Dependencies
      run: yarn install

    - name: Lint
      run: yarn lint
      env:
        NEXT_PUBLIC_INFURA_IPFS_HOSTNAME: makelinterpass.com

    - name: Build
      run: yarn build
      env:
        NEXT_PUBLIC_INFURA_IPFS_HOSTNAME: makelinterpass.com
